name: Broadcast
main: me.virgoth.Broadcast.Broadcast
version: 1.0
description: >
             Broadcasts messages at a set interval.
commands:
  stopbroadcast:
    description: Prevents the broadcasting from continuing.
  startbroadcast:
    description: Initiates the broadcasting process.
